### ISSUE TITLE
napalm_get_facts broken in 228789c6c2e33d437662675c3122ade31087381a

### ISSUE THREAD

**Issue by ipspace** [napalm-automation/napalm-ansible#62]
David already knows what the bug is, this is just a reminder he asked for ;)

Workaround: pass ```args: {}```

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_bEwtxf/ansible_module_napalm_get_facts.py", line 263, in <module>
    main()
  File "/tmp/ansible_bEwtxf/ansible_module_napalm_get_facts.py", line 234, in main
    result = get_func(**args.get(getter, {}))
AttributeError: 'NoneType' object has no attribute 'get'

fatal: [E1]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_bEwtxf/ansible_module_napalm_get_facts.py\", line 263, in <module>\n    main()\n  File \"/tmp/ansible_bEwtxf/ansible_module_napalm_get_facts.py\", line 234, in main\n    result = get_func(**args.get(getter, {}))\nAttributeError: 'NoneType' object has no attribute 'get'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```
