### PR TITLE
If no` arg` is passed default correctly to `{}`

### LINKED ISSUE #62: napalm_get_facts broken in 228789c6c2e33d437662675c3122ade31087381a
David already knows what the bug is, this is just a reminder he asked for ;)

Workaround: pass ```args: {}```

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_bEwtxf/ansible_module_napalm_get_facts.py", line 263, in <module>
    main()
  File "/tmp/ansible_bEwtxf/ansible_module_napalm_get_facts.py", line 234, in main
    result = get_func(**args.get(getter, {}))
AttributeError: 'NoneType' object has no attribute 'get'

fatal: [E1]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_bEwtxf/ansible_module_napalm_get_facts.py\", line 263, in <module>\n    main()\n  File \"/tmp/ansible_bEwtxf/ansible_module_napalm_get_facts.py\", line 234, in main\n    result = get_func(**args.get(getter, {}))\nAttributeError: 'NoneType' object has no attribute 'get'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

### PR DESCRIPTION
**Pull request by dbarrosop**
Fixes #62 

@ipsapce would you mind testing?

Thanks!

### CODE REVIEW

**Comment by targuan** [comment]
Any particular reason to not use the default parameter of the AnsibleModule argument_spec ?
Their is currently three or four different method to set the default values, some standardization could be usefull.
I started to change some of module [there](https://github.com/targuan/napalm-ansible/tree/bugfix/62) but I'd like to finish the integration tests first in order to not break everything again.

**Comment by dbarrosop** [comment]
The only reason is that I am not sure what ansible does with the default argument and it's usually a terrible idea to use mutables as default arguments. In this case it might be safe (depending on how ansible handles default arguments) but due to ignorance on my side I just defaulted to a safe method.

If you are confident it's safe we can apply those changes when we reintroduce your PR.

**Comment by ipspace** [comment]
@dbarrosop Yes, it works. Thanks for a quick fix!
